server:
  port: 8080

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mariadb://localhost:3306/user
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: m0624
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update #update: 변경된 부분만 반영
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #실행되는 쿼리문 보여주기 여부

  profiles:
    include: jwt #이렇게 해서 jwt 관련된 설정은 application-jwt에서 설정해주도록 하겠습니다.

logging:
  level:
    org.springframework.boot.autoconfigure: error
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

jwt:
  secretKey: SecretKeyTest
  header: Authorization # JWT를 검증하는데 필요한 정보
  expirations: 86400 #토큰의 만료시간을 지정함 (단위는 초)

