server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    datasource:
      url: jdbc:mariadb://localhost:3306/user
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: m0624
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update #update: 변경된 부분만 반영
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #실행되는 쿼리문 보여주기 여부


logging:
  level:
    org.springframework.boot.autoconfigure: error
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
